# Generated by Django 2.2.12 on 2020-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_auto_20200407_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
